import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import { ThemeProvider } from "@/lib/components/Theme/ThemeProvider";
import AuthProvider from "@/lib/config/AuthProvider";
import Header from "@/lib/components/Layout/Header";
import Footer from "@/lib/components/Layout/Footer";
import { CartProvider } from "@/lib/context/CartContext";
// import StripeProvider from "@/lib/config/StripeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Foodi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AuthProvider>
          {/* <StripeProvider> */}
          <CartProvider>
            <ThemeProvider attribute="class" defaultTheme="dark">
              <Header />
              {children}
              <ToastContainer
                position="top-center"
                autoClose={2000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                draggable
                theme="dark"
              />
              <Footer />
            </ThemeProvider>
          </CartProvider>
          {/* </StripeProvider> */}
        </AuthProvider>
      </body>
    </html>
  );
}
